version: "3.8"

services:
  db:
    image: postgres:13
    container_name: alpha-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: mcp
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
